# Generated by Django 3.1.6 on 2021-03-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('category', models.CharField(blank=True, choices=[('food', 'Еда'), ('clothes', 'Одежда'), ('stationary', 'Концелярие'), ('cosmetics', 'Косметика'), ('other', 'Разное')], default='other', max_length=300, null=True)),
                ('remainder', models.PositiveSmallIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
